---
bin_dir: /usr/local/bin
working_dir: "{{ tmp_dir }}"
install_dir: /home/ec2-user/install-dir
ssh_public_key_for_ec2_and_openshift_node: "{{ install_config.ssh_key }}"
ssh_private_key_file_for_ec2_and_openshift_node: "{{ install_config.ssh_private_key }}"

state: present

aws_region: "{{ aws.aws_region }}"          # aws region for install
cluster_name: "{{ ocp_cluster.name }}"
base_domain: "{{ ocp_cluster.base_domain }}"
...